//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenScopeChemCad.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenScopeChemCad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] GRNS_LCI_v1_2_05_15 {
            get {
                object obj = ResourceManager.GetObject("GRNS_LCI_v1_2_05_15", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electron	e-	N/A
        ///Iron(2) oxide anion	FeO-	N/A
        ///AsF3..Cl anion	AsClF3-	N/A
        ///AgH2-	H2Ag-	N/A
        ///HAg(H2)	H3Ag	N/A
        ///AgNO+	AgNO+	N/A
        ///AgNO	AgNO	N/A
        ///AgNO-	AgNO-	N/A
        ///AgOO-	AgO2-	N/A
        ///AgAgH	HAg2	N/A
        ///AgAgH-	HAg2-	N/A
        ///AgOAg	Ag2O	N/A
        ///Ag4	Ag4	N/A
        ///Ag5	Ag5	N/A
        ///Ag8	Ag8	N/A
        ///HAlClBr	HAlBrCl	N/A
        ///AlCl2Br	AlBrCl2	N/A
        ///HAlFBr	HAlBrF	N/A
        ///AlF2Br	AlBrF2	N/A
        ///Br(cyc-AlO2)	AlBrO2	N/A
        ///BrAlO2	AlBrO2	N/A
        ///BrAl(O2)2	AlBrO4	N/A
        ///AlClBr2	AlBr2Cl	N/A
        ///AlFBr2	AlBr2F	N/A
        ///HAlBr2	HAlBr2	N/A
        ///HAlFCl	HAlClF	N/A
        ///AlF2Cl	AlClF2	N/A
        ///AlH2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string species {
            get {
                return ResourceManager.GetString("species", resourceCulture);
            }
        }
    }
}
